defaults: &defaults
 AWS_ACCESS_KEY_ID: Your Key ID
 AWS_SECRET_ACCESS_KEY: Your Secret Access Key
 bucket: megamegadeals

development:
 <<: *defaults

test:
 <<: *defaults

production:
 <<: *defaults